stan-core:
  stanPath: .stan
  excludes:
    - docs
    - package-lock.json
  imports:
    '@karmaniverous/get-dotenv':
      - ../get-dotenv/.stan/interop/aws-secrets-manager-tools/**
      - ../get-dotenv/guides/stan-assistant-guide.md
    '@veterancrowd/aws-cli':
      - ../../VeteranCrowd/aws-cli/lib/aws/deleteSecret.js
      - ../../VeteranCrowd/aws-cli/lib/aws/pullSecret.js
      - ../../VeteranCrowd/aws-cli/lib/aws/pushSecret.js
    '@veterancrowd/wrapped-secrets-manager-client':
      - ../../VeteranCrowd/wrapped-secrets-manager-client/lib/WrappedSecretsManagerClient.js
  includes: []
stan-cli:
  cliDefaults:
    run:
      facets: false
      plan: false
      sequential: true
  patchOpenCommand: code -g {file}
  scripts:
    typecheck: npm run typecheck -- --noErrorTruncation
    lint:
      script: npm run lint:fix
      warnPattern: \\d+:\\d+\\s+warning
    test: npm run test -- --no-color
    docs:
      script: npm run docs -- --emit none
      warnPattern: \\[warning\\]
    build: cross-env NO_COLOR=1 npm run build
    knip:
      script: npm run knip
      warnPattern: hints
